version: '3.8'

name: transcendence-dev
services:
  ## Database ##
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_USER: ${POSTGRES_USER:?err}
      POSTGRES_DB: ${POSTGRES_DB:?err}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  front:
    image: ft-transcendance-front-dev:latest
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: front
    restart: unless-stopped
    volumes:
      - ./front/package.json:/app/package.json
      - ./front/pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./front/src:/app/src
    networks:
      - network
    ports:
      - 8080:8080
  
volumes:
  db_data:

networks:
  network:
    driver: bridge
